DataDog/datadog-unix-agent

- agent.py
- dogstatsd.py
Just adding some resilience for better handling of failures to the configuration loading and logging thereafter.
> [yaml][log] fix logging initialization + config load resilience

- omnibus/aix-bootstrap.sh
Unfortunately the experience isn't always wonderful with the script and feels like it might be a WIP for a while. Here are some changes to help us move toward a more resilient and idempotent script we can call consecutively multiple times, producing eventually a working omnibus builder.
The script now also bootstraps the actual agent repo at the specified branch, as opposed to assuming it's already been downloaded. This should allow us to get an omnibus builder ready by running:
```bash
curl https://raw.githubusercontent.com/DataDog/datadog-unix-agent/master/omnibus/aix-bootstrap.sh | bash  
```
> [bootstrap] multiple fixes to script

- utils/hostname.py
- utils/tests/test_hostname.py
Adding support for '_' character in more flexible hostname collection. Still report if a hostname isn't RFC1123 compliant though.
> [hostname] don't enforce RFC1123 compliance on collected hostnames

- omnibus/config/software/datadog-agent-finalize.rb
- omnibus/config/software/pynacl.rb
- omnibus/package-scripts/agent/aix/preinst
- omnibus/package-scripts/agent/aix/prerm
As per the omnibus docs (https://www.rubydoc.info/github/opscode/omnibus/Omnibus/Packager/BFF):
```
The order of the installp scripts is:
- install
* pre-install
* post-install
* config
- upgrade
* pre-remove (of previous version)
* pre-install (previous version of software not present anymore)
* post-install
* config
- remove
* unconfig
* unpre-install
```
This might get slightly confusing at times, but please take a look at the source code if in doubt.
> [omnibus] pyc pre-compile and cleanup

- checks/bundled/lparstats/datadog_checks/lparstats/lparstats.py
Tiny fix to properly use superpowers when available.
Affects hypervisors and entitlement metric collection, see https://github.com/DataDog/datadog-unix-agent/pull/81/files#diff-ed937eae219d6b2b02b88f58da5781dfR37, for instance.
> [lparstats] make sure commands are run with superpowers

- agent.py
- omnibus/package-scripts/agent/aix/postinst
- scripts/install_script.sh
Agent lifecycle should be managed with OS facilities, these might differ on different OS, including the spawning of the agent, it's shutdown, etc. Using the `start/stop` features manually should require a flag to make sure we don't interfere with the OS accidentally.
Also:
- use a more generic name in the installer script for an env variable.
- use color on output error messages
- if running agent straight from source, unpackaged, use a better default location for the pid file.
> [agent] lifecycle should be managed with OS + sneaky script fix

- omnibus/aix-bootstrap.sh
Fixes broken bootstrap script by pinning now that a new `mpfr` lib has been released. That caused `mpfr` and `libffi` to be misaligned causing compiler issues.
This should address it.
> [omnibus] AIX bootstrap script fix

- omnibus/config/patches/psutil/aix-net-kernel-mbuf-header-fix.patch
- omnibus/config/software/psutil.rb
- requirements.txt
**What does this do:**
Bump psutils version to 5.6.5
**Motivation:**
The following fix is needed for the process agent to use getargs for AIX [Fix #1276](https://github.com/giampaolo/psutil/commit/7d8c23d5ce46eaeb13f1ca1910eabf76bdcda6a5)
That fix was released in 5.6.3, however that version was broken due to [Issue #1528](https://github.com/giampaolo/psutil/issues/1528) which got [fixed in 5.6.5](https://github.com/giampaolo/psutil/commit/9be2120e4b6f43a2450c6ddb86fbc1723dd081e5)
> Bump psutils version

- api/handlers.py
Fix a crash when calling the `status` command with multiple process check instances, e.g.:
*process.yaml*:
```
init_config:
instances:
- name: x-service
search_string: ['x-service']
exact_match: False
tags:
- service:x-service
- name: y-service
search_string: ['y-service']
exact_match: False
tags:
- service:y-service
```
> Fix crash when calling `status` with multiple process check

- omnibus/config/patches/psutil/aix-net-kernel-mbuf-header-fix.patch
The [PR #1698](https://github.com/giampaolo/psutil/pull/1698) in the psutil repo broke our patch. This PR aims at fixing that.
> Update psutil patch for version 5.7.0

- omnibus/config/software/jmxfetch.rb
Bintray is shutting down. Let's pull the JAR from Sonatype, similar to what's being done in the Agent 6/7 build in https://github.com/DataDog/datadog-agent/pull/7799.
Testing: I haven't actually run an omnibus build with these changes, but I've verified the updated URL with the default jmxfetch version specified here (`0.23.0`) does point to the same JAR (same sha256 sum).
> [omnibus] Pull JMXFetch JAR from Sonatype

- checks/bundled/disk/datadog_checks/disk/data/conf.yaml.default
Updates to reflect that the disk check doesn't actually support regexes
in the various include/exclude lists.
Ideally, we'd want to add this feature, for now let's update the docs.
> [docs][disk] Update docs in disk default YAML

- checks/bundled/disk/datadog_checks/disk/disk.py
When a parent directory of a mountpoint of a certain device doesn't have effective `x` permissions for the `dd-agent` user, the `disk` check will raise an exception and stop its execution because of that:
```
2021-07-29 11:40:26 EDT | ERROR | dd.agent | collector.collector(collector.py:152) | Traceback disk: Traceback (most recent call last
):
File "/opt/datadog-agent/agent/checks/agent_check.py", line 199, in run
self.check(copy.deepcopy(self.instance))
File "/opt/datadog-agent/embedded/lib/python3.6/site-packages/datadog_checks/disk/disk.py", line 41, in check
try:
File "/opt/datadog-agent/embedded/lib/python3.6/site-packages/psutil/__init__.py", line 2013, in disk_usage
return _psplatform.disk_usage(path)
File "/opt/datadog-agent/embedded/lib/python3.6/site-packages/psutil/_psposix.py", …
```
> [disk] Ensure disk check runs properly when a device is inaccessible

- agent.py
The example yaml uses `enabled`, so it was probably a typo that we check for `enable`.
> Support both dogstatsd.enable and dogstatsd.enabled

- checks/bundled/ibm_was/datadog_checks/ibm_was/ibm_was.py
`tls_verify: false` ignored due to existence of `tls_ca_cert: xxx`. `tls_verify` should dictate whether `tls_ca_cert` is to be used or not, not the other way around.
> Fix `tls_verify: false` overridden by `tls_ca_cert`

- aggregator/tests/test_aggregator.py
- checks/bundled/hmc/datadog_checks/hmc/hmc.py
- requirements-dev.txt
- tasks/test.py
- utils/strings.py
Linters broke on main, so I upgraded them to latest versions - the most notable change is that flake8 doesn't like when a variable is called `l`.
> Upgrade linters and fix new linting issues

- agent.py
We failed to update `AGENT_VERSION` for 1.1.5, so let's release a new version 1.1.6 in which the version is going to be correct.
> Release version 1.1.6

- .github/workflows/codeql-analysis.yml
Static code analysis on datadog-unix-agent using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later.
> Setting up codescanning for datadog-unix-agent

- omnibus/aix-bootstrap.sh
On some SiteOx machines, bundler has problems running, raising errors like:
```
HTTP GET https://index.rubygems.org/versions
Net::OpenTimeout: execution expired
```
This can be caused by DNS issues/irregular setup. The fix is apparently to modify the http.rb file by adding require 'resolv-replace'. See https://github.com/ruby/ruby/pull/597#issuecomment-40507119
> Fix bootstrap script running bundler with DNS issues

- omnibus/aix-bootstrap.sh
- Update coreutils (8.29-3 makes libtool build fail)
- Update Ruby (to be on par with Linux buildimages)
- Install latest SSL certs so Omnibus could properly fetch dependencies
> Fix bootstrap script to get proper machine setup

- checks/bundled/ibm_was/datadog_checks/ibm_was/data/conf.yaml.example
Some customers have a trouble while using an [IBM Websphere Application Server (WAS)](https://www.ibm.com/cloud/websphere-application-platform) in Japanese. This is because an IBM WAS responds a XML in Japanese. 
I wanna add an example `custom_queries` to solve this issue in `conf.yaml.example`.
> Add an example `custom_queries` to solve a Japanese XML issue from IBM WAS
